export interface WardInfo {
    number: string;
    name: string;
}

export const MCD_WARDS: WardInfo[] = [
    { number: "1", name: "NARELA" },
    { number: "2", name: "BANKNER" },
    { number: "3", name: "ALIPUR" },
    { number: "4", name: "BAKHTAWAR PUR" },
    { number: "5", name: "BHALASWA JAHAGIR PUR" },
    { number: "6", name: "MUKUND PUR" },
    { number: "7", name: "BURARI" },
    { number: "8", name: "JHARODA" },
    { number: "9", name: "MALKAGANJ" },
    { number: "10", name: "TIMAR PUR" },
    { number: "11", name: "MUKHERJEE NAGAR" },
    { number: "12", name: "G.T.B. NAGAR" },
    { number: "13", name: "DHIR PUR" },
    { number: "14", name: "ADARASH NAGAR" },
    { number: "15", name: "SARAI PIPAL THALA" },
    { number: "16", name: "JAHANGIRPURI-I" },
    { number: "17", name: "SAMAYPUR BADLI" },
    { number: "18", name: "LIBAS PUR" },
    { number: "19", name: "BHALSWA" },
    { number: "20", name: "JAHANGIR PURI -II" },
    { number: "21", name: "ROHINI" },
    { number: "22", name: "RITHALA" },
    { number: "23", name: "BUDH VIHAR" },
    { number: "24", name: "VIJAY VIHAR" },
    { number: "25", name: "POOTH KALAN" },
    { number: "26", name: "SAHIBABAD DAULAT PUR" },
    { number: "27", name: "BEGUMPUR" },
    { number: "28", name: "BAWANA" },
    { number: "29", name: "KARALA" },
    { number: "30", name: "MUNDAKA" },
    { number: "31", name: "NANGLOI JAT WEST" },
    { number: "32", name: "NILOTHI" },
    { number: "33", name: "PREM NAGAR" },
    { number: "34", name: "NITHARI" },
    { number: "35", name: "KIRARI SULEMAN NAGAR" },
    { number: "36", name: "PRATAP VIHAR" },
    { number: "37", name: "SULTANPURI EAST" },
    { number: "38", name: "MANGOL PURI NORTH" },
    { number: "39", name: "SULTANPUR MAJRA" },
    { number: "40", name: "SULTANPURI SOUTH" },
    { number: "41", name: "GURU HARKISHAN NAGAR" },
    { number: "42", name: "PERAGHARHI" },
    { number: "43", name: "NANGLOI EAST" },
    { number: "44", name: "QUAMMRUDDIN NAGAR" },
    { number: "45", name: "ROHINI SOUTH" },
    { number: "46", name: "MANGOLPURI EAST" },
    { number: "47", name: "MANGOLPURI" },
    { number: "48", name: "MANGOLPURI WEST" },
    { number: "49", name: "ROHINI NORTH" },
    { number: "50", name: "ROHINI CENTRAL" },
    { number: "51", name: "ROHINI EAST" },
    { number: "52", name: "NAHARPUR" },
    { number: "53", name: "PITAMPURA SOUTH" },
    { number: "54", name: "PITAMPUR NORTH" },
    { number: "55", name: "SHALIMAR BAGH NORTH" },
    { number: "56", name: "SHALIMAR BAGH SOUTH" },
    { number: "57", name: "PASCHIM VIHAR SOUTH" },
    { number: "58", name: "PASCHIM VIHAR NORTH" },
    { number: "59", name: "RANI BAGH" },
    { number: "60", name: "SARASWATI VIHAR" },
    { number: "61", name: "TRI NAGAR" },
    { number: "62", name: "RAMPURA" },
    { number: "63", name: "KOHAT ENCLAVE" },
    { number: "64", name: "SHAKUR PUR" },
    { number: "65", name: "NIMRI COLONY" },
    { number: "66", name: "SAWAN PARK" },
    { number: "67", name: "WAJIRPUR" },
    { number: "68", name: "ASHOK VIHAR" },
    { number: "69", name: "KAMLA NAGAR" },
    { number: "70", name: "RANA PRATAP BAGH" },
    { number: "71", name: "SANGAM PARK" },
    { number: "72", name: "MODEL TOWN" },
    { number: "73", name: "SHASTRI NAGAR" },
    { number: "74", name: "INDER LOK COLONY" },
    { number: "75", name: "KISHAN GANJ" },
    { number: "76", name: "DEPUTY GANJ" },
    { number: "77", name: "KASHMERE GATE" },
    { number: "78", name: "MAJNU KA TILA" },
    { number: "79", name: "JAMA MASJID" },
    { number: "80", name: "CHANDNI CHOWK" },
    { number: "81", name: "MINTO ROAD" },
    { number: "82", name: "KUCHA PANDIT" },
    { number: "83", name: "BAZAR SITARAM" },
    { number: "84", name: "TURKMAN GATE" },
    { number: "85", name: "IDGAH ROAD" },
    { number: "86", name: "BALLIMARAN" },
    { number: "87", name: "RAM NAGAR" },
    { number: "88", name: "QASABPURA" },
    { number: "89", name: "PAHAR GANJ" },
    { number: "90", name: "MODEL BASTI" },
    { number: "91", name: "KAROL BAGH" },
    { number: "92", name: "DEV NAGAR" },
    { number: "93", name: "BALIJIT NAGAR" },
    { number: "94", name: "WEST PATEL NAGAR" },
    { number: "95", name: "EAST PATEL NAGAR" },
    { number: "96", name: "NEW RANJIT NAGAR" },
    { number: "97", name: "KIRTI NAGAR" },
    { number: "98", name: "MANSAROWER GARDEN" },
    { number: "99", name: "MOTI NAGAR" },
    { number: "100", name: "KARAM PURA" },
    { number: "101", name: "RAJA GARDEN" },
    { number: "102", name: "RAGHUBIR NAGAR" },
    { number: "103", name: "PUNJABI BAGH" },
    { number: "104", name: "MADIPUR" },
    { number: "105", name: "RAJOURI GARDEN" },
    { number: "106", name: "TAGORE GARDEN" },
    { number: "107", name: "VISHNU GARDEN" },
    { number: "108", name: "KHYALA" },
    { number: "109", name: "JANAK PURI NORTH" },
    { number: "110", name: "NANGAL RAYA" },
    { number: "111", name: "HARI NAGAR" },
    { number: "112", name: "SUBHASH NAGAR" },
    { number: "113", name: "MAHAVIR NAGAR" },
    { number: "114", name: "TILAK NAGAR" },
    { number: "115", name: "MAJOR BHUPINDAR SINGH NAGAR" },
    { number: "116", name: "VIKASPURI EAST" },
    { number: "117", name: "JANAK PURI WEST" },
    { number: "118", name: "JANAK PURI SOUTH" },
    { number: "119", name: "MILAP NAGAR" },
    { number: "120", name: "SITA PURI" },
    { number: "121", name: "KUNWAR SINGH NAGAR" },
    { number: "122", name: "HASTSAL" },
    { number: "123", name: "VIKAS PURI" },
    { number: "124", name: "VIKAS NAGAR" },
    { number: "125", name: "MOHAN GARDEN" },
    { number: "126", name: "NAWADA" },
    { number: "127", name: "UTTAM NAGAR" },
    { number: "128", name: "BINDAPUR" },
    { number: "129", name: "DABRI" },
    { number: "130", name: "MANGLAPURI" },
    { number: "131", name: "SAGARPUR" },
    { number: "132", name: "SAGARPUR WEST" },
    { number: "133", name: "CHHAWLA" },
    { number: "134", name: "NANGLI SAKRAVATI" },
    { number: "135", name: "KAKRAULA" },
    { number: "136", name: "MATIALA" },
    { number: "137", name: "ROSHANPURA" },
    { number: "138", name: "NAJAFGARH" },
    { number: "139", name: "DICHAON KALAN" },
    { number: "140", name: "KHERA" },
    { number: "141", name: "BIJWASAN" },
    { number: "142", name: "RAJ NAGAR" },
    { number: "143", name: "KAPASHERA" },
    { number: "144", name: "MAHIPALPUR" },
    { number: "145", name: "PALAM" },
    { number: "146", name: "SADH NAGAR" },
    { number: "147", name: "MAHAVIR ENCLAVE" },
    { number: "148", name: "MADHU VIHAR" },
    { number: "149", name: "RAJENDER NAGAR" },
    { number: "150", name: "PUSA" },
    { number: "151", name: "INDER PURI" },
    { number: "152", name: "NARAINA" },
    { number: "153", name: "DARYAGANJ" },
    { number: "154", name: "NIZAMUDDIN" },
    { number: "155", name: "LAJPAT NAGAR" },
    { number: "156", name: "BHOGAL" },
    { number: "157", name: "KASTURBA NAGAR" },
    { number: "158", name: "KOTLA MUBARAKPUR" },
    { number: "159", name: "ANDREWSGANJ" },
    { number: "160", name: "AMAR COLONY" },
    { number: "161", name: "MALVIYA NAGAR" },
    { number: "162", name: "HAUZ RANI" },
    { number: "163", name: "SAFDARJANG ENCLAVE" },
    { number: "164", name: "HAUZ KHAS" },
    { number: "165", name: "VASANT VIHAR" },
    { number: "166", name: "MUNIRKA" },
    { number: "167", name: "R. K. PURAM" },
    { number: "168", name: "NANAK PURA" },
    { number: "169", name: "LADOSARAI" },
    { number: "170", name: "MEHRAULI" },
    { number: "171", name: "VASANTKUNJ" },
    { number: "172", name: "KISHANGARH" },
    { number: "173", name: "DEOLI" },
    { number: "174", name: "CHHATARPUR" },
    { number: "175", name: "AYA NAGAR" },
    { number: "176", name: "BHATI" },
    { number: "177", name: "SAID UL AJAIB" },
    { number: "178", name: "SANGAM VIHAR" },
    { number: "179", name: "TIGRI" },
    { number: "180", name: "DAKSHINPURI EXT." },
    { number: "181", name: "KHANPUR" },
    { number: "182", name: "AMBEDKAR NAGAR" },
    { number: "183", name: "MADANGIR" },
    { number: "184", name: "PUSHP VIHAR" },
    { number: "185", name: "TUGHLAKABAD EXTN" },
    { number: "186", name: "SANGAM VIHAR WEST" },
    { number: "187", name: "SANGAM VIHAR CENTRAL" },
    { number: "188", name: "SANGAM VIHAR EAST" },
    { number: "189", name: "CHIRAG DELHI" },
    { number: "190", name: "CHITRANJAN PARK" },
    { number: "191", name: "SHAPUR JAT" },
    { number: "192", name: "GREATER KAILASH-I" },
    { number: "193", name: "SRI NIWASPURI" },
    { number: "194", name: "EAST OF KAILASH" },
    { number: "195", name: "GOVIND PURI" },
    { number: "196", name: "KALKAJI" },
    { number: "197", name: "TUGHLAKABAD" },
    { number: "198", name: "PUL PEHLAD" },
    { number: "199", name: "TEKHAND" },
    { number: "200", name: "HARKESH NAGAR" },
    { number: "201", name: "JAITPUR" },
    { number: "202", name: "MEETHEYPUR" },
    { number: "203", name: "BADAR PUR" },
    { number: "204", name: "MOLARBAND" },
    { number: "205", name: "ZAKIR NAGAR" },
    { number: "206", name: "OKHLA" },
    { number: "207", name: "MADANPUR KHADAR" },
    { number: "208", name: "SARITA VIHAR" },
    { number: "209", name: "MAYUR VIHAR PHASE-I" },
    { number: "210", name: "DALLOPURA" },
    { number: "211", name: "TRILOK PURI" },
    { number: "212", name: "NEW ASHOK NAGAR" },
    { number: "213", name: "KALYAN PURI" },
    { number: "214", name: "KHICHRIPUR" },
    { number: "215", name: "KONDLI" },
    { number: "216", name: "GHAROLI" },
    { number: "217", name: "VINOD NAGAR" },
    { number: "218", name: "MANDAWALI" },
    { number: "219", name: "MAYUR VIHAR PHASE II" },
    { number: "220", name: "PATPARGANJ" },
    { number: "221", name: "KISHAN KUNJ" },
    { number: "222", name: "LAXMI NAGAR" },
    { number: "223", name: "SHAKARPUR" },
    { number: "224", name: "PANDAV NAGAR" },
    { number: "225", name: "ANAND VIHAR" },
    { number: "226", name: "VISHWASH NAGAR" },
    { number: "227", name: "I.P EXTENTION" },
    { number: "228", name: "PREET VIHAR" },
    { number: "229", name: "KRISHNA NAGAR" },
    { number: "230", name: "GEETA COLONY" },
    { number: "231", name: "GHONDLI" },
    { number: "232", name: "ANARKALI" },
    { number: "233", name: "DHARAMPURA" },
    { number: "234", name: "GANDHI NAGAR" },
    { number: "235", name: "AZAD NAGAR" },
    { number: "236", name: "RAGHUBAR PURA" },
    { number: "237", name: "SHAHDARA" },
    { number: "238", name: "JHILMIL" },
    { number: "239", name: "VIVEK VIHAR" },
    { number: "240", name: "DILSHAD COLONY" },
    { number: "241", name: "DILSHAD GARDEN" },
    { number: "242", name: "NEW SEEMA PURI" },
    { number: "243", name: "NAND NAGRI" },
    { number: "244", name: "SUNDER NAGARI" },
    { number: "245", name: "DURGA PURI" },
    { number: "246", name: "ASHOK NAGAR" },
    { number: "247", name: "RAM NAGAR" },
    { number: "248", name: "WELCOME COLONY" },
    { number: "249", name: "CHAUHAN BANGER" },
    { number: "250", name: "ZAFFRABAD" },
    { number: "251", name: "NEW USMANPUR" },
    { number: "252", name: "MAUJPUR" },
    { number: "253", name: "BHAJANPURA" },
    { number: "254", name: "BRAHAM PURI" },
    { number: "255", name: "GHONDA" },
    { number: "256", name: "YAMUNA VIHAR" },
    { number: "257", name: "SUBHASH MOHALLA" },
    { number: "258", name: "KARDAM PURI" },
    { number: "259", name: "JANTA COLONY" },
    { number: "260", name: "BABAR PUR" },
    { number: "261", name: "JIWANPUR" },
    { number: "262", name: "GOKALPUR" },
    { number: "263", name: "SABOLI" },
    { number: "264", name: "HARSH VIHAR" },
    { number: "265", name: "SHIV VIHAR" },
    { number: "266", name: "KARAWAL NAGAR EAST" },
    { number: "267", name: "NEHRU VIHAR" },
    { number: "268", name: "MUSTAFABAD" },
    { number: "269", name: "KHAJOORI KHAS" },
    { number: "270", name: "TUKHMIR PUR" },
    { number: "271", name: "KARAWAL NAGAR WEST" },
    { number: "272", name: "SONIA VIHAR" },
    { number: "CANT 1", name: "DELHI CANTT CHARGE 1" },
    { number: "CANT 2", name: "DELHI CANTT CHARGE 2" },
    { number: "CANT 3", name: "DELHI CANTT CHARGE 3" },
    { number: "CANT 4", name: "DELHI CANTT CHARGE 4" },
    { number: "CANT_5", name: "DELHI CANTT CHARGE 5" },
    { number: "CANT 6", name: "DELHI CANTT CHARGE 6" },
    { number: "CANT 7", name: "DELHI CANTT CHARGE 7" },
    { number: "CANT 8", name: "DELHI CANTT CHARGE 8" },
    { number: "NDMC 1", name: "NDMC CHARGE 1" },
    { number: "NDMC_2", name: "NDMC CHARGE 2" },
    { number: "NDMC_3", name: "NDMC CHARGE 3" },
    { number: "NDMC_4", name: "NDMC CHARGE 4" },
    { number: "NDMC 5", name: "NDMC CHARGE 5" },
    { number: "NDMC_6", name: "NDMC CHARGE 6" },
    { number: "NDMC_7", name: "NDMC CHARGE 7" },
    { number: "NDMC_8", name: "NDMC CHARGE 8" },
    { number: "NDMC_9", name: "NDMC CHARGE 9" }
];
